### ISSUE TITLE
setup.py's use of `open` should explicitly specify encoding

### ISSUE THREAD

**Issue by gaconnet** [CashStar/nap#20]
setup.py includes the text of README.rst using `open('README.rst').read()`. The default behavior for `open` is to open the file in text mode using the system's preferred encoding to decode the file. Since nap's README.rst contains unicode characters encoded in UTF-8, the default behavior of `open` can cause installation to break on systems that have a different preferred encoding.

nap's setup.py should explicitly specify UTF-8 as the encoding when reading README.rst. While Python 3's `open` supports passing an `encoding=` keyword argument, Python 2.7's `open` does not. I think `codecs.open('README.rst', encoding='utf8')` could work across Python 2 & 3.

**Comment by jbane** [comment]
I agree with your assessment on using `codecs.open`. The only caveat I can see is that the encoding format chosen must marshal successfully to and from Python 3 bytes - UTF-8 will fit the bill there.

Python 2: https://docs.python.org/2/library/codecs.html#codecs.open
Python 3: https://docs.python.org/3/library/codecs.html#codecs.open

> encoding specifies the encoding which is to be used for the file. Any encoding that encodes to and decodes from bytes is allowed, and the data types supported by the file methods depend on the codec used.

**Comment by jbane** [comment]
Check this out for testing purposes: https://pymotw.com/3/codecs/#working-with-files

**Comment by neruson** [comment]
Hi folks, just wanted to chime in and suggest taking a look at `io.open` as well. It's a Python 2 backport of the Python 3 built-in `open` functionality, so it might be more familiar to the average user than the `codecs` library.

👋

**Comment by jdsmith** [comment]
Used the io library to specify encoding.
